// Auto-generated file. Do not edit manually.
// Generated from Resources/Win10set *.ico to keep built-in color labels aligned with resource order.
#pragma once

static const LPCWSTR kColorNames[] =
{
    L"Absolute Zero",
    L"Acid green",
    L"Aero blue",
    L"Aero",
    L"African violet",
    L"Air superiority blue",
    L"Alabaster",
    L"Alloy orange",
    L"Almond",
    L"Amaranth 12",
    L"Amaranth pink",
    L"Amaranth purple",
    L"Amaranth red",
    L"Amaranth",
    L"Amazon",
    L"Amber 18",
    L"Amber",
    L"Amethyst",
    L"Android green",
    L"Antique brass",
    L"Antique bronze",
    L"Antique fuchsia",
    L"Antique ruby",
    L"Antique white",
    L"Ao",
    L"Apple green",
    L"Apricot",
    L"Aqua",
    L"Aquamarine",
    L"Arctic lime",
    L"Army green",
    L"Artichoke",
    L"Arylide yellow",
    L"Ash gray",
    L"Asparagus",
    L"Atomic tangerine",
    L"Auburn",
    L"Aureolin",
    L"Avocado",
    L"Azure",
    L"Baby blue eyes",
    L"Baby blue",
    L"Baby pink",
    L"Baker-Miller pink",
    L"Banana Mania",
    L"Barbie Pink",
    L"Barn red",
    L"Battleship grey",
    L"Bdazzled blue",
    L"Beau blue",
    L"Beaver",
    L"Beige",
    L"Big dip o’ruby",
    L"Bisque",
    L"Bistre brown",
    L"Bistre",
    L"Bitter lemon",
    L"Bitter lime",
    L"Bittersweet shimmer",
    L"Bittersweet",
    L"Black bean",
    L"Black chocolate",
    L"Black coffee",
    L"Black coral",
    L"Black olive",
    L"Black Shadows",
    L"Black",
    L"Blanched almond",
    L"Blast-off bronze",
    L"Bleu de France",
    L"Blizzard blue",
    L"Blond",
    L"Blood red",
    L"Blue 78",
    L"Blue 79",
    L"Blue 80",
    L"Blue 81",
    L"Blue 82",
    L"Blue 83",
    L"Blue bell",
    L"Blue gray",
    L"Blue jeans",
    L"Blue sapphire",
    L"Blue yonder",
    L"Blue-gray",
    L"Blue-green 87",
    L"Blue-green",
    L"Blue-violet 91",
    L"Blue-violet 92",
    L"Blue-violet",
    L"Blue",
    L"Bluetiful",
    L"Blush",
    L"Bole",
    L"Bone",
    L"Bottle green",
    L"Brandy",
    L"Brick red",
    L"Bright green",
    L"Bright lilac",
    L"Bright maroon",
    L"Bright navy blue",
    L"Bright yellow",
    L"Brilliant rose",
    L"Brink pink",
    L"British racing green",
    L"Bronze",
    L"Brown sugar",
    L"Brown",
    L"Brunswick green",
    L"Bud green",
    L"Buff",
    L"Burgundy",
    L"Burlywood",
    L"Burnished brown",
    L"Burnt orange",
    L"Burnt sienna",
    L"Burnt umber",
    L"Byzantine",
    L"Byzantium",
    L"Cadet blue 125",
    L"Cadet blue",
    L"Cadet grey",
    L"Cadet",
    L"Cadmium green",
    L"Cadmium orange",
    L"Cadmium red",
    L"Cadmium yellow",
    L"Café au lait",
    L"Café noir",
    L"Cambridge blue",
    L"Camel",
    L"Cameo pink",
    L"Canary yellow",
    L"Canary",
    L"Candy apple red",
    L"Candy pink",
    L"Capri",
    L"Caput mortuum",
    L"Cardinal",
    L"Caribbean green",
    L"Carmine 145",
    L"Carmine",
    L"Carnation pink",
    L"Carnelian",
    L"Carolina blue",
    L"Carrot orange",
    L"Castleton green",
    L"Catawba",
    L"Cedar Chest",
    L"Celadon blue",
    L"Celadon green",
    L"Celadon",
    L"Celeste",
    L"Celtic blue",
    L"Cerise",
    L"Cerulean 162",
    L"Cerulean blue",
    L"Cerulean frost",
    L"Cerulean",
    L"CG blue",
    L"CG red",
    L"Champagne pink",
    L"Champagne",
    L"Charcoal",
    L"Charleston green",
    L"Charm pink",
    L"Chartreuse 171",
    L"Chartreuse",
    L"Cherry blossom pink",
    L"Chestnut",
    L"Chili red",
    L"China pink",
    L"China rose",
    L"Chinese red",
    L"Chinese violet",
    L"Chinese yellow",
    L"Chocolate 181",
    L"Chocolate Cosmos",
    L"Chocolate",
    L"Chrome yellow",
    L"Cinereous",
    L"Cinnabar",
    L"Cinnamon Satin",
    L"Citrine",
    L"Citron",
    L"Claret",
    L"Cobalt blue",
    L"Cocoa brown",
    L"Coffee",
    L"Columbia Blue",
    L"Congo pink",
    L"Cool grey",
    L"Copper 197",
    L"Copper penny",
    L"Copper red",
    L"Copper rose",
    L"Copper",
    L"Coquelicot",
    L"Coral pink",
    L"Coral",
    L"Cordovan",
    L"Corn",
    L"Cornell red",
    L"Cornflower blue",
    L"Cornsilk",
    L"Cosmic cobalt",
    L"Cotton candy",
    L"Coyote brown",
    L"Cream",
    L"Crimson 215",
    L"Crimson",
    L"Crystal",
    L"Cyan 219",
    L"Cyan",
    L"Cyber grape",
    L"Cyber yellow",
    L"Cyclamen",
    L"Dark blue-gray",
    L"Dark brown",
    L"Dark byzantium",
    L"Dark cornflower blue",
    L"Dark cyan",
    L"Dark electric blue",
    L"Dark goldenrod",
    L"Dark green 231",
    L"Dark green",
    L"Dark jungle green",
    L"Dark khaki",
    L"Dark lava",
    L"Dark liver 236",
    L"Dark liver",
    L"Dark magenta",
    L"Dark moss green",
    L"Dark olive green",
    L"Dark orange",
    L"Dark orchid",
    L"Dark pastel green",
    L"Dark purple",
    L"Dark red",
    L"Dark salmon",
    L"Dark sea green",
    L"Dark sienna",
    L"Dark sky blue",
    L"Dark slate blue",
    L"Dark slate gray",
    L"Dark spring green",
    L"Dark turquoise",
    L"Dark violet",
    L"Dartmouth green",
    L"Davys grey",
    L"Deep cerise",
    L"Deep champagne",
    L"Deep chestnut",
    L"Deep jungle green",
    L"Deep pink",
    L"Deep saffron",
    L"Deep sky blue",
    L"Deep Space Sparkle",
    L"Deep taupe",
    L"Denim blue",
    L"Denim",
    L"Desert sand",
    L"Desert",
    L"Dim gray",
    L"Dodger blue",
    L"Dogwood rose",
    L"Drab",
    L"Duke blue",
    L"Dutch white",
    L"Earth yellow",
    L"Ebony",
    L"Ecru",
    L"Eerie black",
    L"Eggplant",
    L"Eggshell",
    L"Egyptian blue",
    L"Eigengrau",
    L"Electric blue",
    L"Electric green",
    L"Electric indigo",
    L"Electric lime",
    L"Electric purple",
    L"Electric violet",
    L"Emerald",
    L"Eminence",
    L"English green",
    L"English lavender",
    L"English red",
    L"English vermillion",
    L"English violet",
    L"Erin",
    L"Eton blue",
    L"Fallow",
    L"Falu red",
    L"Fandango pink",
    L"Fandango",
    L"Fashion fuchsia",
    L"Fawn",
    L"Feldgrau",
    L"Fern green",
    L"Field drab",
    L"Fiery rose",
    L"Fire engine red",
    L"Fire opal",
    L"Firebrick",
    L"Flame",
    L"Flax",
    L"Flirt",
    L"Fluorescent blue",
    L"Forest green 317",
    L"Forest green 318",
    L"Forest green",
    L"French beige",
    L"French bistre",
    L"French blue",
    L"French fuchsia",
    L"French lilac",
    L"French lime",
    L"French mauve",
    L"French pink",
    L"French raspberry",
    L"French rose",
    L"French sky blue",
    L"French violet",
    L"Frostbite",
    L"Fuchsia 333",
    L"Fuchsia purple",
    L"Fuchsia rose",
    L"Fuchsia",
    L"Fulvous",
    L"Fuzzy Wuzzy",
    L"Gainsboro",
    L"Gamboge",
    L"Generic viridian",
    L"Glaucous",
    L"Glossy grape",
    L"GO green",
    L"Gold 346",
    L"Gold 347",
    L"Gold 348",
    L"Gold Fusion",
    L"Gold",
    L"Golden brown",
    L"Golden poppy",
    L"Golden yellow",
    L"Goldenrod",
    L"Gotham green",
    L"Granite gray",
    L"Granny Smith apple",
    L"Gray 358",
    L"Gray",
    L"Green 360",
    L"Green 361",
    L"Green 362",
    L"Green 363",
    L"Green 364",
    L"Green 365",
    L"Green 366",
    L"Green Lizard",
    L"Green Sheen",
    L"Green-blue 368",
    L"Green-blue",
    L"Green-cyan",
    L"Green-yellow 373",
    L"Green-yellow",
    L"Green",
    L"Grullo",
    L"Gunmetal",
    L"Han blue",
    L"Han purple",
    L"Hansa yellow",
    L"Harlequin",
    L"Harvest gold",
    L"Heat Wave",
    L"Heliotrope gray",
    L"Heliotrope",
    L"Hollywood cerise",
    L"Honolulu blue",
    L"Hookers green",
    L"Hot magenta",
    L"Hot pink",
    L"Hunter green",
    L"Iceberg",
    L"Icterine",
    L"Illuminating emerald",
    L"Imperial red",
    L"Inchworm",
    L"Independence",
    L"India green",
    L"Indian red",
    L"Indian yellow",
    L"Indigo dye",
    L"Indigo",
    L"International Klein Blue",
    L"International orange 404",
    L"International orange 405",
    L"International orange",
    L"Iris",
    L"Irresistible",
    L"Isabelline",
    L"Italian sky blue",
    L"Jade",
    L"Japanese carmine",
    L"Japanese violet",
    L"Jasmine",
    L"Jazzberry jam",
    L"Jet",
    L"Jonquil",
    L"June bud",
    L"Jungle green",
    L"Kelly green",
    L"Keppel",
    L"Key lime",
    L"Khaki 424",
    L"Khaki",
    L"Kobe",
    L"Kobi",
    L"Kobicha",
    L"Kombu green",
    L"KSU purple",
    L"Languid lavender",
    L"Lapis lazuli",
    L"Laser lemon",
    L"Laurel green",
    L"Lava",
    L"Lavender 436",
    L"Lavender blue",
    L"Lavender gray",
    L"Lavender",
    L"Lawn green",
    L"Lemon chiffon",
    L"Lemon curry",
    L"Lemon glacier",
    L"Lemon meringue",
    L"Lemon yellow 447",
    L"Lemon yellow",
    L"Lemon",
    L"Liberty",
    L"Light blue",
    L"Light coral",
    L"Light cornflower blue",
    L"Light cyan",
    L"Light French beige",
    L"Light goldenrod yellow",
    L"Light gray",
    L"Light green",
    L"Light orange",
    L"Light periwinkle",
    L"Light pink",
    L"Light salmon",
    L"Light sea green",
    L"Light sky blue",
    L"Light slate gray",
    L"Light steel blue",
    L"Light yellow",
    L"Lilac Luster",
    L"Lilac",
    L"Lime 469",
    L"Lime green",
    L"Lime",
    L"Lincoln green",
    L"Linen",
    L"Lion",
    L"Liseran purple",
    L"Little boy blue",
    L"Liver 477",
    L"Liver 478",
    L"Liver chestnut",
    L"Liver",
    L"Livid",
    L"Macaroni and Cheese",
    L"Madder Lake",
    L"Magenta 484",
    L"Magenta 485",
    L"Magenta 486",
    L"Magenta 487",
    L"Magenta haze",
    L"Magenta",
    L"Magic mint",
    L"Magnolia",
    L"Mahogany",
    L"Maize 493",
    L"Maize",
    L"Majorelle blue",
    L"Malachite",
    L"Manatee",
    L"Mandarin",
    L"Mango Tango",
    L"Mango",
    L"Mantis",
    L"Mardi Gras",
    L"Marigold",
    L"Maroon 504",
    L"Maroon 505",
    L"Maroon",
    L"Mauve taupe",
    L"Mauve",
    L"Mauvelous",
    L"Maximum blue green",
    L"Maximum blue purple",
    L"Maximum blue",
    L"Maximum green yellow",
    L"Maximum green",
    L"Maximum purple",
    L"Maximum red purple",
    L"Maximum red",
    L"Maximum yellow red",
    L"Maximum yellow",
    L"May green",
    L"Maya blue",
    L"Medium aquamarine",
    L"Medium blue",
    L"Medium candy apple red",
    L"Medium carmine",
    L"Medium champagne",
    L"Medium orchid",
    L"Medium purple",
    L"Medium sea green",
    L"Medium slate blue",
    L"Medium spring green",
    L"Medium turquoise",
    L"Medium violet-red",
    L"Mellow apricot",
    L"Mellow yellow",
    L"Melon",
    L"Metallic gold",
    L"Metallic Seaweed",
    L"Metallic Sunburst",
    L"Mexican pink",
    L"Middle blue green",
    L"Middle blue purple",
    L"Middle blue",
    L"Middle green yellow",
    L"Middle green",
    L"Middle grey",
    L"Middle purple",
    L"Middle red purple",
    L"Middle red",
    L"Middle yellow red",
    L"Middle yellow",
    L"Midnight blue",
    L"Midnight green",
    L"Midnight",
    L"Mikado yellow",
    L"Mimi pink",
    L"Mindaro",
    L"Ming",
    L"Minion yellow",
    L"Mint green",
    L"Mint",
    L"Misty moss",
    L"Misty rose",
    L"Mode beige",
    L"Morning blue",
    L"Moss green",
    L"Mountain Meadow",
    L"Mountbatten pink",
    L"MSU green",
    L"Mulberry 571",
    L"Mulberry",
    L"Mustard",
    L"Myrtle green",
    L"Mystic maroon",
    L"Mystic",
    L"Nadeshiko pink",
    L"Naples yellow",
    L"Navajo white",
    L"Navy blue 580",
    L"Navy blue",
    L"Neon blue",
    L"Neon Carrot",
    L"Neon fuchsia",
    L"Neon green",
    L"New York pink",
    L"Nickel",
    L"Non-photo blue",
    L"Nyanza",
    L"Ocean Blue",
    L"Ocean green",
    L"Ochre",
    L"Old burgundy",
    L"Old gold",
    L"Old lace",
    L"Old lavender",
    L"Old mauve",
    L"Old rose",
    L"Old silver",
    L"Olive Drab #7",
    L"Olive Drab",
    L"Olive green",
    L"Olive",
    L"Olivine",
    L"Onyx",
    L"Opal",
    L"Opera mauve",
    L"Orange 608",
    L"Orange 609",
    L"Orange 610",
    L"Orange peel",
    L"Orange soda",
    L"Orange-red 613",
    L"Orange-red",
    L"Orange-yellow 616",
    L"Orange-yellow",
    L"Orange",
    L"Orchid 619",
    L"Orchid pink",
    L"Orchid",
    L"OU Crimson red",
    L"Outer space",
    L"Outrageous Orange",
    L"Oxblood",
    L"Oxford blue",
    L"Pacific blue",
    L"Pakistan green",
    L"Palatinate purple",
    L"Pale aqua",
    L"Pale cerulean",
    L"Pale Dogwood",
    L"Pale pink",
    L"Pale purple",
    L"Pale silver",
    L"Pale spring bud",
    L"Pansy purple",
    L"Paolo Veronese green",
    L"Papaya whip",
    L"Paradise pink",
    L"Parchment",
    L"Paris Green",
    L"Pastel pink",
    L"Patriarch",
    L"Paynes grey",
    L"Peach 645",
    L"Peach puff",
    L"Peach",
    L"Pear",
    L"Pearly purple",
    L"Periwinkle 650",
    L"Periwinkle",
    L"Permanent Geranium Lake",
    L"Persian blue",
    L"Persian green",
    L"Persian indigo",
    L"Persian orange",
    L"Persian pink",
    L"Persian plum",
    L"Persian red",
    L"Persian rose",
    L"Persimmon",
    L"Pewter Blue",
    L"Phlox",
    L"Phthalo blue",
    L"Phthalo green",
    L"Picotee blue",
    L"Pictorial carmine",
    L"Piggy pink",
    L"Pine green",
    L"Pine tree",
    L"Pink 671",
    L"Pink flamingo",
    L"Pink lace",
    L"Pink lavender",
    L"Pink Sherbet",
    L"Pink",
    L"Pistachio",
    L"Platinum",
    L"Plum 679",
    L"Plum",
    L"Plump Purple",
    L"Polished Pine",
    L"Pomp and Power",
    L"Popstar",
    L"Portland Orange",
    L"Powder blue",
    L"Princeton orange",
    L"Process yellow",
    L"Prune",
    L"Prussian blue",
    L"Psychedelic purple",
    L"Puce",
    L"Pullman Brown",
    L"Pumpkin",
    L"Purple 695",
    L"Purple 696",
    L"Purple 697",
    L"Purple mountain majesty",
    L"Purple navy",
    L"Purple pizzazz",
    L"Purple Plum",
    L"Purple",
    L"Purpureus",
    L"Queen blue",
    L"Queen pink",
    L"Quick Silver",
    L"Quinacridone magenta",
    L"Radical Red",
    L"Raisin black",
    L"Rajah",
    L"Raspberry glace",
    L"Raspberry rose",
    L"Raspberry",
    L"Raw sienna",
    L"Raw umber",
    L"Razzle dazzle rose",
    L"Razzmatazz",
    L"Razzmic Berry",
    L"Rebecca Purple",
    L"Red 720",
    L"Red 721",
    L"Red 722",
    L"Red 723",
    L"Red 724",
    L"Red 725",
    L"Red Salsa",
    L"Red-orange 727",
    L"Red-orange 728",
    L"Red-orange",
    L"Red-purple",
    L"Red-violet 732",
    L"Red-violet 733",
    L"Red-violet",
    L"Red",
    L"Redwood",
    L"Resolution blue",
    L"Rhythm",
    L"Rich black 738",
    L"Rich black 739",
    L"Rich black",
    L"Rifle green",
    L"Robin egg blue",
    L"Rocket metallic",
    L"Rojo Spanish red",
    L"Roman silver",
    L"Rose bonbon",
    L"Rose Dust",
    L"Rose ebony",
    L"Rose madder",
    L"Rose pink",
    L"Rose Pompadour",
    L"Rose quartz",
    L"Rose red",
    L"Rose taupe",
    L"Rose vale",
    L"Rose",
    L"Rosewood",
    L"Rosso corsa",
    L"Rosy brown",
    L"Royal blue 760",
    L"Royal blue",
    L"Royal purple",
    L"Royal yellow",
    L"Ruber",
    L"Rubine red",
    L"Ruby red",
    L"Ruby",
    L"Rufous",
    L"Russet",
    L"Russian green",
    L"Russian violet",
    L"Rust",
    L"Rusty red",
    L"Sacramento State green",
    L"Saddle brown",
    L"Safety orange 776",
    L"Safety orange",
    L"Safety yellow",
    L"Saffron",
    L"Sage",
    L"Salmon pink",
    L"Salmon",
    L"Sand dune",
    L"Sand",
    L"Sandy brown",
    L"Sap green",
    L"Sapphire 789",
    L"Sapphire blue",
    L"Sapphire",
    L"Satin sheen gold",
    L"Scarlet",
    L"Schauss pink",
    L"School bus yellow",
    L"Screamin Green",
    L"Sea green 796",
    L"Sea green",
    L"Seal brown",
    L"Selective yellow",
    L"Sepia",
    L"Shadow blue",
    L"Shadow",
    L"Shamrock green",
    L"Sheen green",
    L"Shimmering Blush",
    L"Shiny Shamrock",
    L"Shocking pink 808",
    L"Shocking pink",
    L"Sienna",
    L"Silver 811",
    L"Silver 812",
    L"Silver chalice",
    L"Silver pink",
    L"Silver sand",
    L"Silver",
    L"Sinopia",
    L"Sizzling Red",
    L"Sizzling Sunrise",
    L"Skobeloff",
    L"Sky blue 821",
    L"Sky blue",
    L"Sky magenta",
    L"Slate blue",
    L"Slate gray",
    L"Slimy green",
    L"Smitten",
    L"Smoky black",
    L"Solid pink",
    L"Sonic silver",
    L"Space cadet",
    L"Spanish bistre",
    L"Spanish blue",
    L"Spanish carmine",
    L"Spanish gray",
    L"Spanish green",
    L"Spanish orange",
    L"Spanish pink",
    L"Spanish red",
    L"Spanish sky blue",
    L"Spanish violet",
    L"Spanish viridian",
    L"Spring bud",
    L"Spring Frost",
    L"Spring green 846",
    L"Spring green",
    L"St. Patricks blue",
    L"Star command blue",
    L"Steel blue",
    L"Steel pink",
    L"Steel Teal",
    L"Stil de grain yellow",
    L"Straw",
    L"Strawberry Blonde",
    L"Strawberry",
    L"Sugar Plum",
    L"Sunglow",
    L"Sunray",
    L"Sunset",
    L"Super pink",
    L"Sweet Brown",
    L"Syracuse Orange",
    L"Tan 863",
    L"Tan",
    L"Tangerine",
    L"Tango pink",
    L"Tart Orange",
    L"Taupe gray",
    L"Taupe",
    L"Tea green",
    L"Tea rose 871",
    L"Tea rose",
    L"Teal blue",
    L"Teal",
    L"Telemagenta",
    L"Tenné",
    L"Terra cotta",
    L"Thistle",
    L"Thulian pink",
    L"Tickle Me Pink",
    L"Tiffany Blue",
    L"Timberwolf",
    L"Titanium yellow",
    L"Tomato",
    L"Tropical rainforest",
    L"True Blue",
    L"Trypan Blue",
    L"Tufts blue",
    L"Tumbleweed",
    L"Turquoise blue",
    L"Turquoise green",
    L"Turquoise",
    L"Turtle green",
    L"Tuscan brown",
    L"Tuscan red",
    L"Tuscan tan",
    L"Tuscan",
    L"Tuscany",
    L"Twilight lavender",
    L"Tyrian purple",
    L"UA blue",
    L"UA red",
    L"Ultra pink",
    L"Ultra red",
    L"Ultramarine blue",
    L"Ultramarine",
    L"Umber",
    L"Unbleached silk",
    L"United Nations blue",
    L"University of Pennsylvania red",
    L"Unmellow yellow",
    L"UP Forest green",
    L"UP maroon",
    L"Upsdell red",
    L"Uranian blue",
    L"USAFA blue",
    L"Van Dyke brown",
    L"Vanilla ice",
    L"Vanilla",
    L"Vegas gold",
    L"Venetian red",
    L"Verdigris",
    L"Vermilion 923",
    L"Vermilion",
    L"Veronica",
    L"Violet 926",
    L"Violet 927",
    L"Violet 928",
    L"Violet 929",
    L"Violet-blue 931",
    L"Violet-blue",
    L"Violet-red",
    L"Violet",
    L"Viridian green",
    L"Viridian",
    L"Vivid burgundy",
    L"Vivid sky blue",
    L"Vivid tangerine",
    L"Vivid violet",
    L"Volt",
    L"Warm black",
    L"Weezy Blue",
    L"Wheat",
    L"Wild blue yonder",
    L"Wild orchid",
    L"Wild Strawberry",
    L"Wild watermelon",
    L"Windsor tan",
    L"Wine dregs",
    L"Wine",
    L"Winter Sky",
    L"Wintergreen Dream",
    L"Wisteria",
    L"Wood brown",
    L"Xanadu",
    L"Xanthic",
    L"Xanthous",
    L"Yale Blue",
    L"Yellow 960",
    L"Yellow 961",
    L"Yellow 962",
    L"Yellow 963",
    L"Yellow 964",
    L"Yellow 965",
    L"Yellow Orange 970",
    L"Yellow Orange",
    L"Yellow Sunshine",
    L"Yellow-green 967",
    L"Yellow-green 968",
    L"Yellow-green",
    L"Yellow",
    L"YInMn Blue",
    L"Zaffre",
    L"Zomp"
};
